[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm ci --legacy-peer-deps"]

[phases.build]
cmds = ["chmod +x build.sh && ./build.sh"]

[start]
cmd = "npx serve dist/frontend -s -l 8080"

[staticAssets]
directory = "dist/frontend"
